server:
  port: 7081

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: payment-commands
          content-type: application/json
          group: payment
        output:
          destination: payment-events
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181

#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: payment
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer