server:
  port: 7081

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: order-flow
          content-type: application/json
          group: payment
        output:
          destination: order-flow
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092
          zkNodes: zookeeper:2181