apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot1
  name: springboot1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot1
    spec:
      containers:
      - image: eu.gcr.io/io-capco-692719302307-trai/bradesco/springboot1
        imagePullPolicy: Always
        name: springboot1
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot1
  name: springboot1
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot1
  type: ClusterIP
status:
  loadBalancer: {}