apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJldS5nY3IuaW8iOnsidXNlcm5hbWUiOiJjYXRhcmluYS5jYXN0cm9AY2FwY28uaW8iLCJwYXNzd29yZCI6IkVkdWNhY2FvMjAxMiIsImF1dGgiOiJZMkYwWVhKcGJtRXVZMkZ6ZEhKdlFHTmhjR052TG1sdk9rVmtkV05oWTJGdk1qQXhNZz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: image-registry
type: kubernetes.io/dockerconfigjson
